import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import logo from "../public/logo.svg";
import { NavButton } from "../components/NavButton";
import { Button } from "../components/Button";
import { BsArrowDownCircle } from "react-icons/bs";
import { AiFillInstagram } from "react-icons/ai";
import { HiOutlineMail } from "react-icons/hi";
import NextLink from "next/link";
import About from "../pages/about/index";
import Skills from "../pages/skills/index";
import Hobbies from "./hobbies";
import Projects from "./projects";

const Home: NextPage = () => {
  return (
    <div className={styles.pages_container}>
      <div className={styles.container}>
        <Head>
          <title>Suman Biswas</title>
          <meta name="sumanbiswas" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav className={styles.navbar}>
          <div className={styles.navbar_logo}>
            <Image src={logo} width={60} height={60} />
          </div>
          <NavButton />
        </nav>
        <main className={styles.main}>
          <div className={styles.main_container}>
            <div className={styles.main_container_image_container_mobile}>
              <div className={styles.main_container_image_container_circle}>
                <img
                  className={styles.main_container_image_container_hero_img}
                  src="./home/my_img.webp"
                />
              </div>
            </div>
            <div className={styles.main_container_text_container}>
              <h1 className={styles.main_container_text_container_header}>
                Suman <br /> Biswas.
              </h1>
              <h1
                className={styles.main_container_text_container_header_mobile}
              >
                Suman Biswas.
              </h1>
              <p className={styles.main_container_text_container_text_small}>
                sutdent, web &amp; app dev
              </p>
              <Button text="hire me" href="/" style="dark" />
              <Button
                text="resume"
                href="https://drive.google.com/file/d/1gbo8yzCoMlM6foz54ZSEXhB4ApDX8YAY/view?usp=sharing"
                style="white"
              />
            </div>
            <div className={styles.main_container_image_container}>
              <div className={styles.main_container_image_container_circle}>
                <img
                  className={styles.main_container_image_container_hero_img}
                  src="./home/my_img.webp"
                />
              </div>
            </div>
          </div>
        </main>
        <footer className={styles.footer}>
          <BsArrowDownCircle
            className={styles.down_arrow}
            color="#333333"
            size={30}
          />
          <div className={styles.footer_contact_mail_container}>
            <NextLink href={"https://www.instagram.com/sumanbiswas7/"}>
              <AiFillInstagram
                className={styles.footer_contact_mail_container_icon}
                color="#333333"
                size={29}
              />
            </NextLink>
            <NextLink href={"http://sumanbiswas842001@gmail.com"}>
              <HiOutlineMail
                className={styles.footer_contact_mail_container_icon}
                color="#333333"
                size={30}
              />
            </NextLink>
          </div>
        </footer>
      </div>
      <About />
      <Skills />
      <Hobbies />
      <Projects />
    </div>
  );
};

export default Home;
